//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterOK
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseSet
    {
        public int id { get; set; }
        public int idProduct { get; set; }
        public int idProvider { get; set; }
    
        public virtual ProductSet ProductSet { get; set; }
        public virtual ProviderSet ProviderSet { get; set; }
    }
}
